name: xl_eyepetozer
description: A new Flutter project.
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # 1.用于显示隐藏 flutter 的 splash screen
  flutter_splash_screen: ^0.3.0
  # 2.toast 库
  fluttertoast: ^8.0.7
  # 3.网络访问库
  http: ^0.13.3
  # 4.InheritedWidget的包装器 ，使它们更易于使用和更可重用。
  provider: ^5.0.0
  # 5.State Manager、Navigation Manager
  get: 4.2.4
  # 6.banner左右滑动需要
  flutter_swiper: ^1.1.6
  # 7.图片扩展库
  extended_image: ^4.1.0
  # 8.下拉刷新和上拉加载的库
  pull_to_refresh: ^2.0.0
  # 9.依赖于Dart常用工具类库common_utils，以及对其他第三方库封装
  flustars: ^2.0.1
  # 10.分享
  share_plus: ^2.1.4
  # 11.视频播放库
  video_player: ^2.1.12
  # 12.对 video_player库 进行了一层封装，便于上层使用
  chewie: ^1.0.0
  # 13.常见动画库
  animations: ^2.0.1
  # 14.允许展开和折叠文本
  readmore: ^2.1.0
  # 15.webView 插件
  flutter_webview_plugin: ^0.4.0
  # 16.加载更多
  loading_more_list: ^4.0.1
  # 17.图片处理库
  photo_view: ^0.12.0
  # 18.数据缓存库
  shared_preferences: ^2.0.6
  # 19.用于从图像库中选取图像，并使用相机拍摄新照片
  image_picker: ^0.8.3
  # 20.侧滑列表项，侧滑删除、更多、分享等
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/